name: Lints and Builds
on:
  workflow_call:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: yarn

      - name: Lint
        run: yarn lint-test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: yarn

      - name: Build
        run: |
          export DEV_PUBLIC_URL="https://assets.rebustokenred.com/portal/"
          export TESTNET_PUBLIC_URL="https://assets.rebustestnet.com/portal/"
          export TESTNET_DOMAIN_URL="https://app.rebustestnet.com/"
          export MAINNET_PUBLIC_URL="https://assets.rebuschain.com/portal/"
          export MAINNET_DOMAIN_URL="https://app.rebuschain.com/"
          export NODE_OPTIONS="--max_old_space_size=4096"
          yarn 'react-env:testnet'
          mv public/__ENV.js public/__ENV.js.testnet
          yarn 'react-env:mainnet'
          mv public/__ENV.js public/__ENV.js.mainnet
          yarn 'react-env:alphanet'

          yarn build:css && yarn build

          sed -i -r "s/public\/__ENV.js/public\/__ENV.js?q=$(date +%s)/g" ./prod/index.html
          cp ./prod/index.html ./prod/index.testnet.html
          cp ./prod/index.html ./prod/index.mainnet.html
          sed -i -r "/manifest\.json/! s/(src|href)=\"[^h]([^\"]*)\"/\1=\"${DEV_PUBLIC_URL//\//\\/}\2\"/g" ./prod/index.html
          sed -i -r "s/https:\/\/app.rebustokenred.com\//${TESTNET_DOMAIN_URL//\//\\/}/g" ./prod/index.testnet.html
          sed -i -r "/manifest\.json/! s/(src|href)=\"[^h]([^\"]*)\"/\1=\"${TESTNET_PUBLIC_URL//\//\\/}\2\"/g" ./prod/index.testnet.html
          sed -i -r "s/https:\/\/app.rebustokenred.com\//${MAINNET_DOMAIN_URL//\//\\/}/g" ./prod/index.mainnet.html
          sed -i -r "/manifest\.json/! s/(src|href)=\"[^h]([^\"]*)\"/\1=\"${MAINNET_PUBLIC_URL//\//\\/}\2\"/g" ./prod/index.mainnet.html

          sed -i -r "s/url\(\/assets/url\(\.\/assets/g" ./prod/styles.css

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: prod
