name: Tests, Build, and Deploys UI to Branch
on:
  push:
    branches:
      - '**'
      - '!master'
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-lint:
    uses: rebuschain/rebus.app.web/.github/workflows/action-build-lint.yml@fix-epic-branch-pt2

  dispatch:
    runs-on: ubuntu-latest
    needs: [build-lint]
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          repository: rebuschain/rebus.app.deploy
          event-type: branch-ui
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
