name: Deploys Nginx to Dev
on:
  push:
    branches:
      - '**'
      - '!master'
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  publish-dev:
    uses: rebuschain/rebus.app/.github/workflows/action-publish-nginx.yml@master
    with:
      env: dev
    secrets:
      aws_region: ${{ secrets.AWS_REGION }}
      aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      project: ${{ secrets.DEV_NGINX_PROJECT }}
      domain: ${{ secrets.DEV_DOMAIN }}

  deploy-dev:
    uses: rebuschain/rebus.app/.github/workflows/action-deploy-ecs.yml@master
    needs: [publish-dev]
    with:
      env: dev
      task_definition: nginx/taskdefinition.template.json
    secrets:
      aws_region: ${{ secrets.AWS_REGION }}
      aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      project: ${{ secrets.DEV_NGINX_PROJECT }}
      service: ${{ secrets.DEV_NGINX_SERVICE }}
      cluster: ${{ secrets.DEV_NGINX_CLUSTER }}
      aws_log_group: ${{ secrets.DEV_NGINX_AWS_LOG_GROUP }}
      task_role_arn: ${{ secrets.DEV_NGINX_TASK_ROLE_ARN }}
      task_execution_role_arn: ${{ secrets.DEV_NGINX_TASK_EXECUTION_ROLE_ARN }}
